services: 
  geoserver:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
    #  >
    #  sh -c "cd cmd && ./app"
      >  
      sh -c "cd cmd && go run main.go"
    ports: 
      - '${APP_PORT:-8080}:${APP_PORT:-8080}'
    volumes:
      - ./:/app
      - ./resource:/app/resource
    networks:
      - app_network
    mem_limit: '${MEM_LIMIT:-2G}'     # Устаревшее для docker-compose
    deploy:
      resources:
        limits:
          memory: '${MEM_LIMIT:-2G}'
          cpus: '${CPUS_COUNT:-2}'
networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.123.45.0/24
          gateway: 10.123.45.1
