services: 
  geoserver:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
    #  >
    #  sh -c "cd cmd && ./app"
      >  
      sh -c "cd cmd && go run main.go"
    # ports: 
    #   - '${APP_PORT:-8080}:${APP_PORT:-8080}'
    volumes:
      - ./:/app
      - ./resource:/app/resource
    networks:
      - app_network
    mem_limit: '${MEM_LIMIT:-2G}'     # Устаревшее для docker-compose
    deploy:
      resources:
        limits:
          memory: '${MEM_LIMIT:-2G}'
          cpus: '${CPUS_COUNT:-2}'
  nginx-cache:
      image: nginx:alpine
      ports:
        - '${APP_PORT:-8080}:${APP_PORT:-8080}'
      volumes:
        - ./resource/cache:/var/cache/static:rw
        - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      depends_on:
        - geoserver
      networks:
        - app_network
      restart: unless-stopped
      environment:
      - APP_PORT=${APP_PORT:-8080}
      command: >
        sh -c "
          envsubst '$$APP_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
          nginx -g 'daemon off;'
        "
networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.123.45.0/24
          gateway: 10.123.45.1
